### ISSUE TITLE
Typo in peerDependency?

### ISSUE THREAD

**Issue by dbartholomae** [cherryblossom000/typedoc-plugin-param-names#2]
Hi there!

The peerDependency to typedoc is set to `<0.18`. Is this supposed to be `>=0.18`? I can confirm that the plugin is working for me with typedoc `0.19.3`, and with the new peerDependencies resolution mechanism this dependency conflict now stops me from installing the plugin.

Best,
Daniel

**Comment by cherryblossom000** [comment]
Hi, thanks for using this plugin! I set the range to `<0.18` because when I created this plugin, `0.17` was the latest version. According to semver, breaking changes can occur between minor versions when the major number is `0`.

I've updated the range to `>=0.15.5 <0.20`, so `0.19` is supported in the latest release. `0.15.5` was the earliest version of typedoc that this plugin worked with, so this shouldn't be a breaking change.
